# 服务端口
server:
  port: 8081
# 数据链接，请注意修改你自己数据库和账号密码
spring:
  application:
    #  serviceId.   细节：名称不能有大写，名称不能有下划线
    name: kuangstudy-user-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.233.51:3306/kuangstudy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: admin
# mybatis的配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.cloud.pojo
  configuration:
    map-underscore-to-camel-case: true

